### ISSUE TITLE
DOI badge points to Krylov.jl

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/KnetNLPModels.jl#46]
Also need to insert correct DOI in CITATION.bib.

**Comment by paraynaud** [comment]
I opened #47.

I followed the step of [this tutorial](https://scottishsnow.wordpress.com/2019/09/03/doi-for-your-code/) to create a DOI from a github repository, but I can't access KnetNLPModels.jl repository anymore, because it is module JSO module now.
None of the repositories from JSO appeared in the selection that I could make.

Do you have a hint for me?

**Comment by amontoison** [comment]
You can keep this DOI badge :-)

**Comment by dpo** [comment]
Actually, the badge seems ok now for some reason. Could you just update the citation file?
